CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE clientes (
    id_cliente numeric(18,0) NOT NULL,
    nome_cliente varchar(100) NOT NULL,
    cpf varchar(11) NOT NULL,
    email varchar(100) NOT NULL,
    data_cadastro timestamp NOT NULL,
    data_nascimento date NOT NULL,
    CONSTRAINT pk_clientes PRIMARY KEY (id_cliente)
);

CREATE TABLE produtos (
    id_produto integer GENERATED BY DEFAULT AS IDENTITY,
    descricao varchar(100) NOT NULL,
    preco numeric(18,2) NOT NULL,
    estoque integer NOT NULL DEFAULT 0,
    CONSTRAINT pk_produtos PRIMARY KEY (id_produto)
);

CREATE TABLE usuarios__sistema (
    id_usuario integer GENERATED BY DEFAULT AS IDENTITY,
    usuario character varying(100) NOT NULL,
    senha character varying(255) NOT NULL,
    token_acesso uuid,
    CONSTRAINT pk_usuarios_sistema PRIMARY KEY (id_usuario)
);

CREATE TABLE pedidos (
    id_pedido integer GENERATED BY DEFAULT AS IDENTITY,
    cliente_id integer NOT NULL,
    data_pedido timestamp NOT NULL DEFAULT (NOW()),
    total numeric(18,2) NOT NULL,
    CONSTRAINT pk_pedidos PRIMARY KEY (id_pedido),
    CONSTRAINT fk_pedidos_clientes FOREIGN KEY (cliente_id) REFERENCES clientes (id_cliente) ON DELETE RESTRICT
);

CREATE TABLE pedido__produtos (
    id_pedido_produto integer GENERATED BY DEFAULT AS IDENTITY,
    pedido_id integer NOT NULL,
    produto_id integer NOT NULL,
    quantidade integer NOT NULL,
    preco_unitario numeric(18,2) NOT NULL,
    data_do_pedido timestamp NOT NULL,
    CONSTRAINT pk_pedido_produtos PRIMARY KEY (id_pedido_produto),
    CONSTRAINT fk_pedido_produtos_pedidos FOREIGN KEY (pedido_id) REFERENCES pedidos (id_pedido) ON DELETE CASCADE,
    CONSTRAINT fk_pedido_produtos_produtos FOREIGN KEY (produto_id) REFERENCES produtos (id_produto) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX ix_clientes_cpf ON clientes (cpf);

CREATE INDEX "IX_pedido__produtos_pedido_id" ON pedido__produtos (pedido_id);

CREATE INDEX "IX_pedido__produtos_produto_id" ON pedido__produtos (produto_id);

CREATE INDEX "IX_pedidos_cliente_id" ON pedidos (cliente_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250508102544_InitialCreate', '9.0.4');

COMMIT;

